### PR TITLE
igb-avb: sync to igb-5.3.2

### PR DESCRIPTION
**Pull request by pinealservo**
I'm re-targeting @htfujina's pull request to open-avb-next.

### CODE REVIEW

**Comment by htfujina** [comment]
This adds changes to the README.

**Comment by htfujina** [comment]
Just as a comment - I'm an igb maintainer at Intel.

**Comment by andrew-elder** [comment]
Looks ok to me - EricM?

**Comment by eric-mann** [comment]
Looks good to me. Thanks Todd!

**Pull request merged**
