### PR TITLE
Markdown translation of Chris's gPTP design document

### PR DESCRIPTION
**Pull request by pinealservo**
It seems to have carried over pretty well.  I only had to fix one section of markup.

Here's the link to the file in my fork of Open-AVB so you can see how it renders: https://github.com/pinealservo/Open-AVB/blob/open-avb-next/documents/design/AVnu_gPTP_Code.md

### CODE REVIEW

**Comment by andrew-elder** [comment]
Looks good to me. Is there and easy way to add a table of contents to the top to aid navigation?

**Comment by pinealservo** [comment]
I made a version in asciidoc format instead of markdown to get a ToC; github's asciidoc renderer is a lot more powerful, and asciidoc is arguably better for technical writing anyway: https://github.com/pinealservo/Open-AVB/blob/open-avb-next/documents/design/AVnu_gPTP_Code.asciidoc

**Comment by pinealservo** [comment]
If you're okay with one or the other, let me know and I'll clean up the history a bit and remove the other one.

**Comment by andrew-elder** [comment]
I'm 100% ok with the asciidoc version. Thanks!

**Comment by pinealservo** [comment]
OK, I cleaned up the history a bit and left only the asciidoc version.  See http://asciidoctor.org/ for the documentation on the asciidoc library that github uses; it's a pretty nice tool.

**Pull request merged**
