### PR TITLE
Fixes: #276 - Problems with receiving frames longer than 256 bytes.

### PR DESCRIPTION
**Pull request by MarcinMiklasSTC**
Function igb_add_rx_frag taken from before commit:

AVNu/Open-AVB/2fdb56a391e9e09ff22837e56d594507fbaf9250

### CODE REVIEW

**Comment by andrew-elder** [comment]
Looks good to me. Intel guys?

**Comment by htfujina** [comment]
the igb_reset_q_vector is a change I have in my tree and is a typo that should be fixed.

The other one I'm waiting on Eric to comment on. I've been working on that over the weekend but I didn't get as far as Jakub.

**Comment by andrew-elder** [comment]
@htfujina, so are you saying we should merge the pull request as is?

**Comment by htfujina** [comment]
I don't know much about the github interface. If there are TWO requests, one is good, the other should wait for Eric. If there is ONE, then wait for Eric.

**Comment by andrew-elder** [comment]
You can look at pull requests here https://github.com/AVnu/Open-AVB/pulls

**Comment by andrew-elder** [comment]
This looks good to me. @intel-ethernet  - ok by you?

**Comment by eric-mann** [comment]
Looks good to me.

**Pull request merged**
