### PR TITLE
igb-avb: fix builds on 3.19 kernels et al

### PR DESCRIPTION
**Pull request by htfujina**
Fix builds on recent kernels.

Signed-off-by: Todd Fujinaka <todd.fujinaka@intel.com>

### CODE REVIEW

**Comment by andrew-elder** [comment]
Looks ok to me. Anyone from Intel?

**Comment by htfujina** [comment]
It was wrong. I have a newer fix.

**Comment by andrew-elder** [comment]
Still waiting for someone from Intel to sign off on this. Eric, Chris?

**Comment by andrew-elder** [comment]
@intel-ethernet - comments?

**Comment by eric-mann** [comment]
I'm assuming Todd knows what he is doing since he is the official maintainer of the standard igb driver for Intel :).

**Comment by andrew-elder** [comment]
Good to know!

**Pull request merged**
