### PR TITLE
Open avb next: Simple_listener multiple stream

### PR DESCRIPTION
**Pull request by pcub**
Hello all,

As discussed in: https://github.com/AVnu/Open-AVB/issues/264

It works as individual streamID filter, when simple_listener run one by one.
But it does not work when I run two simple_listener simultaneously. 

It is better to enhance the functionality for listening multiple streams.

Thank you.

### CODE REVIEW

**Comment by intel-ethernet** [comment]
Are the changes to kcompat.h intentional ?

Re: Bandwidth2(): I generally wonder about the fidelity to the Qav/FTQSS/MSRP specs however which describe packet rate x packet size per observation interval vs a ‘bytes per sec’ reinterpretation. I’m not religiously devoted to this … I just wonder about overall consistency between MSRP and the underlying HW shapers …

ekm

**Comment by pcub** [comment]
@intel-ethernet  
Are you asking from me?

**Comment by andrew-elder** [comment]
As far as I can tell, this pull request is a "clean" pull request from "next" to "master". Discussion on kcompat.h should take place on the open-avb-next branch via a new issue if that is required. Unless anyone objects in the next 48 hours, I'm going to go ahead and complete the pull request.

**Comment by andrew-elder** [comment]
@pcub - pull requests from open-avb-next to master should not have any new commits in them, or in fact fix any issues. They are more like "housekeeping" pull requests. Was this pull request intentional?

**Comment by pcub** [comment]
I am not familiar with github and pull request stuffs. I am using first time these things. I discussed about simple_listener functionality and someone told me that we are welcome for full request.

**Comment by pinealservo** [comment]
@pcub, a pull request is used to submit code you write to a project.  Instead of getting commit access to every repository you contribute to, you work on a clone of the project's repository and, when you have a set of changes ready to submit, you issue a pull request that references the development branch on your fork and the project repository branch that you are working from.  This lets the project maintainers review your code and suggest changes before it's merged.

When someone says, "you are welcome to submit a pull request," that means that if *you* implement the feature you would like, it can be merged into the main repository. It is a polite way to suggest that we are not planning on working on it in the near term, and if you really need the feature you will need to implement it yourself.

**Pull request closed without merging**
