### PR TITLE
AVTP pipeline is using gptplocaltime() function

### PR DESCRIPTION
**Pull request by MarcinMiklasSTC**
+ ini files fixes and makefile improvement

### CODE REVIEW

**Comment by andrew-elder** [comment]
This looks like fairly basic cleanup to me and all looks ok. Anyone else?

**Comment by MarcinMiklasSTC** [comment]
Can you please merge it soon? I am working on bigger change which depends on this pull request but I don't want to add more commits here since they won't be trivial.

**Comment by andrew-elder** [comment]
I need another reviewer to say ok. Ken, David, Levi?

**Comment by kencarlino** [comment]
I have reviewed the commits in this pull request and found no issues.

**Pull request merged**
