### PR TITLE
gPTP: Log output and Dox comment updates only

### PR DESCRIPTION
**Pull request by andrew-elder**

### CODE REVIEW

**Comment by pinealservo** [comment]
Huh, the new review request feature didn't show up as a comment. I like that it shows the approved/change required intent, though.

**Comment by andrew-elder** [comment]
Can someone else please take a quick look and review? I have further changes pending....

**Comment by bdthomsen** [comment]
The changes look good to me.

**Comment by andrew-elder** [comment]
@bdthomsen - thanks!

**Pull request merged**
