### PR TITLE
Feature avtp pipeline

### PR DESCRIPTION
**Pull request by andrew-elder**
merge AVTP pipeline to open-avb-next

### CODE REVIEW

**Comment by davidcemin** [comment]
It looks good to me.

**Comment by MarcinMiklasSTC** [comment]
There is couple of run_*.sh scripts in root directory of repo added on feature-avtp-pipeline branch. They were added to make development of avtp_pipeline easier, I'm not sure if they deserve to be in open-avb-next and then in master branch.

But this doesn't prevent this pull request from merging. We can remove the files we do not like in separate pull request.

**Comment by andrew-elder** [comment]
Thank you for the comments @MarcinMiklasSTC. I'll create a new issue to review the run_*.sh scripts in the root dir.

**Comment by andrew-elder** [comment]
Any further comments from anyone before this pull request is merged?

**Comment by andrew-elder** [comment]
Last chance for comments on this pull request. Will plan to merge tomorrow morning.

**Pull request merged**
